### ISSUE TITLE
error 404 

### ISSUE THREAD

**Issue by aym3n-afk** [codalab/codabench#832] opened 2023-05-02 10:22 UTC
nothing works. code Job .

**Comment by Didayolo** [comment] 2023-05-02 13:08
Please be more specific. What URL gives you a 404 error? To what it is supposed to redirect?

**Comment by ihsaan-ullah** [comment] 2023-05-03 10:51
@juli-99  I tried to reproduce your error.

Steps:

1. Seach for a public competition e.g. [AUTOGRAPH BENCHMARK](https://www.codabench.org/competitions/353/)
2. Register for the competition
3. An email will be sent like this:
<img width="541" alt="Screenshot 2023-05-03 at 3 45 23 PM" src="https://user-images.githubusercontent.com/13259262/235895741-374a8490-9ca9-4981-8240-4b8e83147804.png">
4. Click on the link in the email to access the competition (In this case it works)


I think the problem you are having is because you tried to register to a competition which is private and you are NOT an admin fo the competition. In this case if you only use the URL without secret key (in your case: [R&S Engineering Competition 2023 Qualifying](https://www.codabench.org/competitions/784/)), your will get 404 error because the competition is private/unpublished.

If this is not the case, please share more details

Thanks.

**Comment by Didayolo** [comment] 2023-05-03 12:21
Indeed, it is because the competition is private. The email contains the public URL, not the secret URL. Not sure if we should do something about it.

**Comment by juli-99** [comment] 2023-05-04 10:02
> The email contains the public URL, not the secret URL. Not sure if we should do something about it.

Did I understand you correctly that you are not sure if you should fix broken links?

**Comment by Didayolo** [comment] 2023-05-04 12:51
Yes, but the link is not actually broken. The fact that you can't access it is not a bug, it's a feature, since the competition is private. But I am not sure that the email should contain the private URL. Maybe it should? It needs to be discussed.

**Comment by Didayolo** [comment] 2023-05-04 22:47
I close this issue as it is solved by #839. The fix will be merged soon.

**Closed by Didayolo** 2023-05-04 22:47 UTC
