### ISSUE TITLE
Email sent has logo issue

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1566] opened 2024-08-21 13:20 UTC
Email sent to users has logo problem and useless unsubscribe link
<img width="641" alt="Screenshot 2024-08-21 at 6 20 13 PM" src="https://github.com/user-attachments/assets/04e05e52-5ca8-4dd1-927e-4dc39a2ba295">

**Comment by Didayolo** [comment] 2024-08-21 13:54
Duplicate of #1460

**Closed by Didayolo** 2024-08-21 13:54 UTC
Labels: Bug
