### ISSUE TITLE
Latex 

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codabench#1016] opened 2023-07-14 16:05 UTC
Is latex not working in Codabench or is there a problem from my side

<img width="293" alt="Screenshot 2023-07-14 at 9 04 23 PM" src="https://github.com/codalab/codabench/assets/13259262/939e36f6-cb0f-4f3d-b4bc-d94450d4c5ec">

**Comment by Didayolo** [comment] 2023-07-18 09:34
Indeed LaTeX is not rendered in Markdown pages.

I close this issue because it is a duplicate of this one: 

- #852

**Closed by Didayolo** 2023-07-18 09:34 UTC
