### ISSUE TITLE
[feature] Create and modify competition tasks by script

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1070] opened 2023-08-10 21:18 UTC
Hi,

I am wondering if there is a feature that allows me to update the tasks in a competition using an automated script (a bot), which includes:
-  Scoring Program
- Ingestion Program
- Input Data
- Reference Data

This feature would help development drastically because very time I make a minor change to any of these 4, I need to manually:
- upload it in the Resource tab
- create a new task
- replace old tasks with new ones in the competition

Thanks.

**Comment by ihsaan-ullah** [comment] 2023-08-11 09:18
Duplicate of #742

**Comment by Didayolo** [comment] 2023-08-11 10:00
I close this issue as it is a duplicate of #742. It is indeed a very important feature, as shown by the "P1" (priority 1) label on the original issue.

**Closed by Didayolo** 2023-08-11 10:00 UTC
