### ISSUE TITLE
Phase end time is not changeable

### ISSUE THREAD

**Issue by MarcosMaldonadoMerino** [codalab/codabench#1598] opened 2024-09-27 12:36 UTC
Hi there, im currently an administrator of a competition with 90 participants (https://www.codabench.org/competitions/3583/) and we are having problems changing the end time of our competition phase called "Fase 1: Tablero preliminar". We need to set the end time to October 2 03:00 GMT-0 or 00:00 GMT-3 but when trying the GUI only permits to set a Date, setting automatically the end time to October 2 00:00 GMT-0 or October 1 21:00 GMT-3. In Chile, the country the competition is running on, this means that competitors have 3 less hours to make submissions.

![image](https://github.com/user-attachments/assets/565b2dad-ea53-46af-ab9d-7adcb2f0cdfe)

![image](https://github.com/user-attachments/assets/c4393b1f-91f1-45aa-b18a-f768d25e8121)

Also as presented in #1155, we also want to create a instantly following phase but it seemes like is impossible. This is less urgent.

Is there a way that you guys can help us setting the end time of our competition phase (with id=6193) to 03:00 GMT-0? We need to fix this urgently as our competition rules stipulate that end time.

**Comment by Didayolo** [comment] 2024-10-03 14:29
Indeed, this problem is already reported here: #1155.

As a work-around, we'll see if we can manually change the time for your specific competition.
We'll get back to you soon.

**Comment by MarcosMaldonadoMerino** [comment] 2024-10-03 15:58
Hi, this is no longer needed. We change our competition dates rules as a work-around, but its clear that this feature is crucial to fit other countries time zones. We will notify you guys if we need to change another date manually as our competition ends this weekend.

**Comment by Didayolo** [comment] 2024-10-07 12:25
Thanks for the reply. This change is now present on #1616. I close this issue for now, especially as it is a duplicate of #1155.

**Closed by Didayolo** 2024-10-07 12:25 UTC
