### ISSUE TITLE
competition duplicate listing

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#884] opened 2023-05-18 15:06 UTC
Hi,

One of my competitions appears two times in the benchmark management. The call to https://www.codabench.org/api/competitions/?mine=true&type=any does list the same competition two times (id 821):

```json
[
    {
        "id": 746,
        "title": "…",
        "created_by": "louisbeziaud",
        "created_when": "2023-04-19T16:36:06.048671Z",
        "published": false,
        "logo": "…",
        "description": "…",
        "competition_type": "competition"
    },
    {
        "id": 821,
        "title": "…",
        "created_by": "louisbeziaud",
        "created_when": "2023-05-15T07:43:20.559603Z",
        "published": false,
        "logo": "…",
        "description": "…",
        "competition_type": "competition"
    },
    {
        "id": 821,
        "title": "…",
        "created_by": "louisbeziaud",
        "created_when": "2023-05-15T07:43:20.559603Z",
        "published": false,
        "logo": "…",
        "description": "…",
        "competition_type": "competition"
    }
]
```

This is not blocking at all for me but might indicate some issue at benchmark creation. I can't say exactly but I did create, delete and recreate the competition (same name, different bundle). There might be some race condition?

**Comment by Didayolo** [comment] 2023-05-22 11:12
That may be a never reported issue, or a new problem caused by recent changes (e.g. #843 or #859).

On my side it never occured. Do you have any idea of what could be different with this benchmark?

**Comment by ihsaan-ullah** [comment] 2023-05-22 11:39
I think this is introduced by the new changes made.

The pattern looks like the number of rows = number of admins added in the competition

<img width="274" alt="Screenshot 2023-05-22 at 4 38 43 PM" src="https://github.com/codalab/codabench/assets/13259262/31e30ca9-2254-4767-ae45-39602400b295">

I have 4 admins added in this competition

**Comment by lbeziaud** [comment] 2023-05-22 12:36
@Didayolo Apart from the rapid creation/deletion/creation I don't see anything particular with this benchmark. It contains 12 tasks, maybe that's a lot? I might have deleted the benchmark while its tasks where still being created. Note that the second bundle submission defined the same tasks. But I'm completely guessing here.

@ihsaan-ullah I don't think it's related to the number of admins. I've added admins (total 3 now) and it still appears 2 times, and it was appearing 2 times with only one admin.

**Comment by Didayolo** [comment] 2023-05-25 11:22
Should be fixed by the PR above (not deployed yet).

**Closed by Didayolo** 2023-05-25 11:22 UTC
Labels: Bug
