### ISSUE TITLE
n/a scores on top of leaderboard when using “Force best”

### ISSUE THREAD

**Issue by ndido98** [codalab/codabench#1640] opened 2024-10-28 07:59 UTC
I am hosting a private competition on Codabench (https://www.codabench.org/competitions/4188/) and we are running into an issue when the participants’ submissions fail the scoring step.

In particular, the score produced is n/a, which is good by itself. However, this score is always placed on top of the leaderboard, and when participants make new submissions to override the failed one the n/a score remains.
Also, we organizers have to manually delete any n/a submissions to force the display of the correct score.

**Comment by Didayolo** [comment] 2024-10-28 10:28
Hi @ndido98, thank you for reporting this issue.

I close this issue because it is a duplicate of #1284.

**Closed by Didayolo** 2024-10-28 10:28 UTC
