### ISSUE TITLE
n/a scores on leaderboard

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#1152] opened 2023-09-11 11:21 UTC
Hi,

There seems to be an issue with unevaluated tasks or missing scores.

If we look at the scores of submission ID 18231 on competition https://www.codabench.org/competitions/880/ we have:

```
Task 1/12: N/A
Task 2/12: 0.5249526350152358
Task 3/12: 0.4500405614331665
... 
```

Reruning two times I first got (ID 18289): 

```
Task 1: N/A
Task 2: N/A
Task 3: 0.4500405614331665 
```
then (ID 18302):

```
Task 1: 0.49426542068915713
Task 2: 0.5249526350152358
Task 3: N/A 
```

The scorer is working successfully with this submission on my laptop.

I thought it could be related to https://github.com/codalab/codabench/issues/1055 since the leaderboard was set to "Force latest multiple" but I switched it to "Add and delete multiple" before trying a third rerun and still got N/A values. Also the inconsistency make me think it is a different issue.

**Comment by lbeziaud** [comment] 2023-09-18 10:13
I tried with an execution time limit of 1200 and the issue is the same.

Looking at the leaderboard this appear to be a recent issue, with most n/a appearing after 24/08/2023. On 16/09/2023 there was a mix of successful submissions (17) and failed ones (10), with up to 11/12 missing values (two times). Same thing on 24/08/2023, 17 good submissions and 21 with missing values.

Is there a limit on the number of times the scorer is evaluated? Since we have 12 tasks that might be related.

This is breaking the challenges 879 and 880. Any idea of an option to change on our part?

**Comment by Didayolo** [comment] 2023-09-18 13:21
What queue are you using? How many workers do you have listening to that queue?

The jobs for different tasks are supposed to run in parallel on the different workers, I wonder if this could be linked to the problem.

**Comment by ihsaan-ullah** [comment] 2023-09-18 13:24
From #1022 and #1055, it looks like the problem comes from the leaderboard rule (Force last etc) or when you run a submission when the previous is not finished. Still needs investigation

**Comment by tristan-allard** [comment] 2023-09-22 08:11
Dear @Didayolo and @ihsaan-ullah,  

Any idea? 
I am sorry to insist, the challenges 879 and 880 are at stake :( (end Oct 1st) 

Thanks a lot for your help

**Comment by ihsaan-ullah** [comment] 2023-09-22 12:20
@tristan-allard 

can you please provide 

- the competition bundle
- instructions to reproduce the bug
- sample submission which generates the bug

please make sure that the sample submission does not take hours to run.

**Comment by lbeziaud** [comment] 2023-09-22 12:32
@ihsaan-ullah Here are the [submission.zip](https://github.com/codalab/codabench/files/12700665/submission.zip) and [bundle.zip](https://github.com/codalab/codabench/files/12700666/bundle.zip) with correspond to the submission and competition of my first message. Reproducing the issue is done by submitting the file, which leads to missing values although it should not. Reruning the submission multiple times leads to different missing values.

**Comment by ihsaan-ullah** [comment] 2023-09-22 14:52
@lbeziaud what is the leaderboard rule Add, Force Last, Force last multiple etc

**Comment by lbeziaud** [comment] 2023-09-22 14:55
@ihsaan-ullah currently "add and delete multiple", but the bug is also present with "force latest multiple" and with "add"

**Comment by ihsaan-ullah** [comment] 2023-09-22 17:22
I have seen this bug cannot reproduce it again

Here are my submissions:
<img width="1293" alt="Screenshot 2023-09-22 at 10 21 23 PM" src="https://github.com/codalab/codabench/assets/13259262/4eb68e80-e5a2-44f6-85cf-2e2085a5616e">

Here are the results: 
[Results - Playground(31).csv](https://github.com/codalab/codabench/files/12703096/Results.-.Playground.31.csv)

**Comment by ihsaan-ullah** [comment] 2023-09-22 17:22
Have you observed any specific pattern when this happens?

**Comment by lbeziaud** [comment] 2023-09-22 17:53
I have not observed anything particular. The issue is easily reproducible with https://www.codabench.org/competitions/879/ and https://www.codabench.org/competitions/880/. The later is not the official competition and can be used for testing if needed. Could your results be computed on a different queue than ours? The fact that the issue was not present at first might also a change on this side. I don't think I have access to the execution state in the API (?) but it looks like a (random) subset of tasks is simply not executed at all.

**Comment by ihsaan-ullah** [comment] 2023-09-23 06:40
> I have not observed anything particular. The issue is easily reproducible with https://www.codabench.org/competitions/879/ and https://www.codabench.org/competitions/880/. The later is not the official competition and can be used for testing if needed.

I am going to check 880

> Could your results be computed on a different queue than ours?

No if I am using your competition 880

> The fact that the issue was not present at first might also a change on this side.

Do you mean a problem with the queue?

> I don't think I have access to the execution state in the API (?) but it looks like a (random) subset of tasks is simply not executed at all.

I think all tasks are executed, as can be seen in the submission logs. But the problem could be in writing the scores to the leaderboard.

**Comment by lbeziaud** [comment] 2023-09-25 06:18
I think I found the source of the issue. The N/A values are due to an issue with docker failing to pull. Looking at the API, I get:
```
    "status": "Failed",
    "status_details": "Pull for codalab/codalab-legacy:py37 failed!",
```
for the children of a submission which have a missing score (like https://www.codabench.org/api/submissions/18232/).
The error is not visible in the interface, which might be something to fix.

**Comment by ihsaan-ullah** [comment] 2023-09-25 07:40
> I think I found the source of the issue. The N/A values are due to an issue with docker failing to pull. Looking at the API, I get:
> 
> ```
>     "status": "Failed",
>     "status_details": "Pull for codalab/codalab-legacy:py37 failed!",
> ```
> 
> for the children of a submission which have a missing score (like https://www.codabench.org/api/submissions/18232/). The error is not visible in the interface, which might be something to fix.

I have seen n/a for submissions which have successfully run (score visible in the scoring logs). But this maybe the cause.
Docker pull error is shown now in the logs too after this PR #1161

**Comment by lbeziaud** [comment] 2023-09-27 14:28
@ihsaan-ullah the children of your submissions have status "Preparing" (eg https://www.codabench.org/api/submissions/19720/). Is there something I can do about that?

**Comment by ihsaan-ullah** [comment] 2023-09-27 15:09
> @ihsaan-ullah the children of your submissions have status "Preparing" (eg https://www.codabench.org/api/submissions/19720/). Is there something I can do about that?

Are these submissions running on Codabench queue or your private queue?

**Comment by lbeziaud** [comment] 2023-09-27 21:46
> I have seen n/a for submissions which have successfully run (score visible in the scoring logs). 

I looked a bit more into that. I got all submissions from challenges 879 and 880 by querying https://www.codabench.org/api/submissions/ and filtering for phases 1476 and 1475 (corresponding to the two challenges).

Looking at non-cancelled children submissions I get the following values (with duplicates dropped and hostname removed) when the score is present:

| status     | status_details                  |
| :--------- | :------------------------------ |
| Finished   | scoring_hostname-...            |
| Finished   | hostname-...                    |
| Finished   | nan                             |

and the following when the score is missing:

| status      | status_details                                                   |
| :---------- | :--------------------------------------------------------------- |
| Failed      | Could not find scores file, did the scoring program output it?   |
| Failed      | Failure updating submission data.                                |
| Failed      | Pull for codalab/codalab-legacy:py37 failed!                     |
| Finished    | hostname-...                                                     |
| Preparing   | nan                                                              |
| Scoring     | hostname-...                                                     |
| Scoring     | ingestion_hostname-...                                           |
| Submitted   | nan                                                              |

"n/a for submissions which have successfully run" should correspond to status="Finished" and status_details="nan", which is not present. Or did you observe that on other challenges?

Note that status="Preparing" and status="Scoring" corresponds to your three stuck submissions, and the status="Submitted" is a submission which was made during my experiment.

**Comment by Didayolo** [comment] 2023-09-27 22:44
I haven't followed everything here, but I was thinking, maybe the scoring program should be investigated too? In #1022, the problem was linked to the scoring program.

**Comment by lbeziaud** [comment] 2023-09-27 22:49
@Didayolo True, I am currently downloading every submissions to validate the scoring program. However the fact that the n/a values appear on a *random* subset of columns could not come from that. Also the issue appears to be quite recent which is surprising. I'll edit this answer with results.

**Comment by ihsaan-ullah** [comment] 2023-09-28 07:20
Interesting:

I am not sure why we have `hostname-...` because we should either have `scoring_hostname-...` or `ingestion_hostname-...`.

I will check when and why we have the status_detail for failed submissionsa

**Comment by lbeziaud** [comment] 2023-09-28 09:14
@ihsaan-ullah if it helps I get the following stats:

```
curl 'https://www.codabench.org/api/submissions/?format=json' -H 'Cookie: ...' | jq '.[] | select( .has_children == false ) | .status_details ' | sort | uniq -c
```

|     |  status_details                                                     |
|-----|-------------------------------------------------------|
|   2 | "Docker pull for codalab/codalab-legacy:py37 failed!" |
|   2 | "Failure updating submission data."                   |
| 167 | "hostname-173cb64efd54"                               |
| 126 | "hostname-24a8ff4e90c4"                               |
|  41 | "hostname-3d7bf952edaa"                               |
| 153 | "hostname-4d258d086963"                               |
| 165 | "hostname-c8e2a6691ce3"                               |
| 243 | "hostname-f53f8ce6f0b1"                               |
|   1 | "ingestion_hostname-2819f1ed4b89"                     |
|   3 | "ingestion_hostname-2aca1f91c841"                     |
|   1 | "ingestion_hostname-3f98cb844363"                     |
|   1 | "ingestion_hostname-88ac01106d75"                     |
|   1 | "ingestion_hostname-8d9b0cd2cc6a"                     |
|   1 | "ingestion_hostname-afdb7bf1e5ab"                     |
|   1 | "ingestion_hostname-dac369b54ed8"                     |
|   1 | "ingestion_hostname-f6cdf6462bdb"                     |
| 572 | null                                                  |
| 365 | "Pull for codalab/codalab-legacy:py37 failed!"        |
|  40 | "scoring_hostname-2819f1ed4b89"                       |
|   1 | "scoring_hostname-2aca1f91c841"                       |
|  37 | "scoring_hostname-3af382caaa35"                       |
|  38 | "scoring_hostname-3f98cb844363"                       |
|   1 | "scoring_hostname-88ac01106d75"                       |
|   5 | "scoring_hostname-8d9b0cd2cc6a"                       |
|  34 | "scoring_hostname-afdb7bf1e5ab"                       |
|  39 | "scoring_hostname-dac369b54ed8"                       |
|   3 | "scoring_hostname-de6f62df65c3"                       |
|   3 | "scoring_hostname-f6cdf6462bdb"                       |

**Comment by ihsaan-ullah** [comment] 2023-09-28 09:28
@lbeziaud can you also show submission status and date

**Comment by lbeziaud** [comment] 2023-09-28 09:51
@ihsaan-ullah here [a.csv](https://github.com/codalab/codabench/files/12748061/a.csv)

**Comment by ihsaan-ullah** [comment] 2023-09-28 09:55
> @ihsaan-ullah here [a.csv](https://github.com/codalab/codabench/files/12748061/a.csv)

how to check which ones are with n/a score in this csv?

**Comment by lbeziaud** [comment] 2023-09-28 09:57
@ihsaan-ullah oh sorry I forgot the column. Here [a.csv](https://github.com/codalab/codabench/files/12748110/a.csv) is a version with the last column indicating if `scores` is missing (true) or not (false)

**Comment by lbeziaud** [comment] 2023-09-28 10:46
@ihsaan-ullah [a.csv](https://github.com/codalab/codabench/files/12748542/a.csv) last column is true if the score is missing (sorry I deleted my previous answer by mistake)

**Comment by lbeziaud** [comment] 2023-10-01 08:53
@ihsaan-ullah I tried to re-run some submissions multiple times on a custom queue. Everything seems fine with that: I get no N/A and the submissions you made that were stuck in "Running" state are now fine. I do think the issue was indeed "Pull for codalab/codalab-legacy:py37 failed!" for the missing scores, and something else for the endless "Running" state, but cannot know without the actual logs. I guess the issue is with the default queue. Concerning the pulling issue, it is surprising that the image has to be pulled multiple times.

**Comment by ihsaan-ullah** [comment] 2023-10-01 08:58
> @ihsaan-ullah I tried to re-run some submissions multiple times on a custom queue. Everything seems fine with that: I get no N/A and the submissions you made that were stuck in "Running" state are now fine. I do think the issue was indeed "Pull for codalab/codalab-legacy:py37 failed!" for the missing scores

This seems reasonable.

> and something else for the endless "Running" state, but cannot know without the actual logs.

This needs investigation

> I guess the issue is with the default queue. Concerning the pulling issue, it is surprising that the image has to be pulled multiple times.

This is happening because when you have n tasks, one submission is replicated n times and when the submission is sent to the compute worker, it treats it as an independent submissions and pulls the docker image  for it. I think this is a chosen way to do it and not a bug.

**Comment by lbeziaud** [comment] 2023-10-01 09:01
Oh I just realized one score is actually missing https://www.codabench.org/api/submissions/20674/. I'll investigate that since I have access to the queue now

**Comment by Didayolo** [comment] 2023-10-24 15:11
Not sure how related it is, but here is my bug report:

### Conditions

- Multiple tasks (10 tasks)
- Add/remove multiple submission rule
- Added several submissions made with the same account

### Symptoms

- The first submission worked
- The other have n/a scores

<img width="1153" alt="Capture d’écran 2023-10-24 à 17 10 07" src="https://github.com/codalab/codabench/assets/11784999/9375ef12-ee44-449d-b487-e7555442dade">

**Comment by Didayolo** [comment] 2023-10-26 18:21
The change is deployed on Codabench default queue. I close the issue for now. Please report it if the problems continue to occur.

**Closed by Didayolo** 2023-10-26 18:21 UTC
Labels: Bug, P1
