### ISSUE TITLE
Display bug (n/a) when force submission to the leaderboard

### ISSUE THREAD

**Issue by starsholic** [codalab/codabench#1275] opened 2024-01-14 08:51 UTC
Hi,

When I force participants' submission to the leaderboard, though the submission is successfully evaluated, the results in the leaderboard show n/a as below.
<img width="749" alt="截屏2024-01-14 16 45 37" src="https://github.com/codalab/codabench/assets/52476332/3482955c-97b6-47d6-a010-a0e84b963f6a">

The competition leaderboard is https://www.codabench.org/competitions/1772/#/results-tab

Thanks!

**Comment by ihsaan-ullah** [comment] 2024-01-14 09:17
I think the rule is applied to the new submissions and not the old ones. I see that the two n/a scores are coming from cancelled and failed submissions. Please add manually the submissions for these users to fix the problem

Note: Submission with a tick sign is on the leaderboard
<img width="1093" alt="Screenshot 2024-01-14 at 2 16 08 PM" src="https://github.com/codalab/codabench/assets/13259262/f845fde9-693b-43c7-bf67-ecee29e7bb76">
<img width="1090" alt="Screenshot 2024-01-14 at 2 16 20 PM" src="https://github.com/codalab/codabench/assets/13259262/c3d963a1-6870-4912-be90-f7c62db3a295">

**Comment by starsholic** [comment] 2024-01-14 09:43
Thanks for your reply.

Since the number of submissions is large (about 1365 submissions currently), adding the best result for each user manually seems pretty hard.
Can I filter out the canceled or failed results? 

Thanks

**Comment by ihsaan-ullah** [comment] 2024-01-15 12:52
> Thanks for your reply.
> 
> Since the number of submissions is large (about 1365 submissions currently), adding the best result for each user manually seems pretty hard. Can I filter out the canceled or failed results automantically?
> 
> Thanks

Yes, you can filter using the status dropdown

**Comment by starsholic** [comment] 2024-01-15 13:02
![image](https://github.com/codalab/codabench/assets/52476332/d9b75fa3-5e78-4279-bc85-e313efb32b47)
Thanks! In fact, I can't delete all the cancelled files with one click, as the top-right button is grey.

Besides, I'm quite confused why the 'force best' will choose the 'n/a' results. Could we just filter this automantically without delete all the 'n/a' submissions?

**Comment by ihsaan-ullah** [comment] 2024-01-15 13:11
I think you cannot delete someone else's submission even if you are the organizer.

What you can do is to identify users on your leaderboard for which you see `n/a` then go to submissions panel, find the user using the search and add their good submission to leaderboard manually.

After this if the n/a problem reappears, please report it so that we can check the problem

**Comment by starsholic** [comment] 2024-01-15 13:16
Thanks! But the user and submission are quite large...(185 participants and 1579 submissions), means it is hard to find the best result of each user.
Can we just change the 'force best' strategy and make it do not to select the 'n/a' result?

**Comment by ihsaan-ullah** [comment] 2024-01-15 13:20
You can try force last multiple or force last rule

force last multiple: adds multiple submissions to leaderboard per user (all new submitted)
force last: adds the latest (only one) submission per user to the leaderboard

**Comment by ihsaan-ullah** [comment] 2024-01-15 13:28
I see the problem now. I am labelling this as a bug and we will check and resolve it soon.

**Comment by starsholic** [comment] 2024-01-15 13:51
That's nice. Thank you very much!

**Comment by Didayolo** [comment] 2024-01-18 17:19
Related issue:

- #1055

**Comment by ihsaan-ullah** [comment] 2024-01-28 13:44
@starsholic can you reproduce this bug in a new competition?

**Comment by starsholic** [comment] 2024-01-29 02:43
@ihsaan-ullah  Ok, I will try it today.

**Comment by starsholic** [comment] 2024-02-01 11:01
Seems still have bug. https://www.codabench.org/competitions/1772/#/results-tab
![1706785287825](https://github.com/codalab/codabench/assets/52476332/1904023a-0d6e-42ff-b1d7-190683e37d21)

**Comment by ihsaan-ullah** [comment] 2024-02-01 11:06
Yes the bug is there, I am unable to reproduce it on my side. Can you reproduce it in another challenge where we don't have these many submissions and participants?

**Comment by starsholic** [comment] 2024-02-01 11:34
I copied a same competition here (https://www.codabench.org/competitions/1969/#/participate-tab), seems there are two steps to reproduce the bug.
1. submit a correct submission
2. submit a failed submission
![1706787245431](https://github.com/codalab/codabench/assets/52476332/badd5a37-d014-4640-bee1-26ba48cdf524)

**Comment by starsholic** [comment] 2024-02-02 10:14
Hi @ihsaan-ullah ,
Now 'force last' meets the same issue as 'force best', the leaderboard is here: https://www.codabench.org/competitions/1772/#/results-tab

**Comment by Didayolo** [comment] 2024-02-09 19:09
Thank you for the additional investigation. I hope we'll be able to resolve this bug soon.

**Comment by Didayolo** [comment] 2024-07-24 16:49
I close this issue to merge and keep track of it here: #1540.

**Closed by Didayolo** 2024-07-24 16:49 UTC
Labels: Bug
